### ISSUE TITLE
Package.json not found

### ISSUE THREAD

**Issue by Asarew** [ganemone/NodeRequirer#1]
Hey, just found a little snag in the code.
it only looks in the first directory of you workfolders, so lets say i have the following structor

```
project/
- README
- package.json
- src/
-- index.js
-- otherfile.js
```

in this case i always have 2 workfolders: "project" and "src", because i work in the src directory and almost never in the project directory (ofcourse).

NodeRequirer then looks for the package.json in the first workfolder and not in the rest, so i get a nice FileNotFoundError:

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/Projects/project/src/package.json'
```

even though i have the project directory as a workfolder but just not as the first workfolder, if i place it on top everything works fine.

so it would be nice if NodeRequirer looks in every workfolder and not just the first one it finds

**Comment by damianb** [comment]
It *might* be a good idea, tbh, to tell users to define the project root as an absolute path, then. Just hit this problem and was flustered for a bit.

**Comment by ganemone** [comment]
It does say so explicitly in the readme.

> IMPORTANT: In order for node-requirer to parse your project correctly, you must have a .sublime-project file configured with the absolute path to your project

**Comment by damianb** [comment]
@ganemone Saying so in the error message itself would be far more prudent.

**Comment by dantman** [comment]
I've been contemplating how necessary this requirement even is. Now that I wrote findup() finding a `package.json` should actually be just a matter of doing `utils.findup(os.path.dirname(view.file_name()), 'package.json')`.

I can't think of any context where NodeRequirer works but there is no file_name to identify the correct package root.
