### ISSUE TITLE
Can't require css files

### ISSUE THREAD

**Issue by tnrich** [ganemone/NodeRequirer#100]
Hey there,

Often I am requiring both .js files AND .css or .scss files in my project. Currently NodeRequirer does not allow me to search for paths that end in .css (or similar).

For example:
![image](https://cloud.githubusercontent.com/assets/2730609/20903769/83ed1f80-baf1-11e6-9d13-27ef96d0b537.png)

It would be great if .css files were searchable as well. Any chance you could make this happen @ganemone ?

Thanks!

**Comment by megawac** [comment]
What else would people like to support importing. I'm adding a `importable_extensions` variable and would like suggestions on what to include in it. So far here is my list that I import day to day:

```
    "importable_extensions": [
        "js", "jsx", "tsx", "json",
        "css", "less", "scss",
        "svg", "jpg", "png", "gif"
    ],
```
