### ISSUE TITLE
Nothing happens on ctrl+shift+i

### ISSUE THREAD

**Issue by PavelPolyakov** [ganemone/NodeRequirer#19]
Hi,

Just installed the NodeRequirer to by sublime 3.

![image](https://cloud.githubusercontent.com/assets/839290/5410755/2f7648c6-8201-11e4-82b1-186696159631.png)

But when I press ctrl+shift+i - nothing happens, when I choose the same from the menu (on the screenshot) - nothing happens.

The *.sublime-project looks the next:
~~~
{
	"folders":
	[
		{
			"follow_symlinks": true,
			"path": "."
		}
	]
}
~~~

I've also tried with the absolute path - nothing happens.

Are there some points so I can check if it's working or not?

Regards,

**Comment by garthk** [comment]
I *was* suffering this. Sometime after I used `⌘⇧P` and `req` to get it working, `^⇧I` started working.

**Comment by Sparragus** [comment]
I am trying what @garthk suggests but it still does not work for me. `⌘⇧P` and `Require` on the menu also did not work.

**Comment by ganemone** [comment]
@Sparragus - What OS are you using? Also, can you check your python console for errors and paste them here?

**Comment by Sparragus** [comment]
I'm using Mac OS X 10.10.1 and Sublime Text 3. How do I check the python console for errors? FWIW, I have Python 2.7.8.

**Comment by ganemone** [comment]
http://lmgtfy.com/?q=check+python+console+in+sublime+text

(Control+` )

**Comment by Sparragus** [comment]
Aha! It needs to have a `package.json` with the dependencies listed. If you don't use the `package.json`, it does not work. Also, if something is not listed as a dependency, it wont work. Here is the console error:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text 3.app/Contents/MacOS/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "Require in /Users/richardkaufman/Library/Application Support/Sublime Text 3/Installed Packages/NodeRequirer.sublime-package", line 40, in run
  File "Require in /Users/richardkaufman/Library/Application Support/Sublime Text 3/Installed Packages/NodeRequirer.sublime-package", line 45, in load_file_list
  File "Require in /Users/richardkaufman/Library/Application Support/Sublime Text 3/Installed Packages/NodeRequirer.sublime-package", line 68, in parse_package_json
FileNotFoundError: [Errno 2] No such file or directory: '/Users/richardkaufman/code/tutorials/stream-adventure/package.json'
```

**Comment by ganemone** [comment]
Correct. All that information should be in the docs. If you feel the docs are insufficient feel free to submit a PR making them more clear.

**Comment by Sparragus** [comment]
Thank you!
