### ISSUE TITLE
Require specific export from file

### ISSUE THREAD

**Issue by ganemone** [ganemone/NodeRequirer#26]
At some point, I want to add support for parsing files to look for exports.(something). This would likely be a separate command due to performance issues, i.e. only parse the file if necessary. 

Example:

```javascript
// File Being Imported
exports.something = function something(...)
exports.anotherThing = function anotherThing(...)

// Importing file
var {something, anotherThing} = require('somefile');
// OR....
var something = require('somefile').something;
// OR...
var somefile = require('somefile');
var something = somefile.something;
var anotherThing = somefile.anotherThing;
```

Object decomposition would be an option. Then a menu would show the possible exports from the file when requiring it, and the user would choose which ones they would like to require.

**Comment by dantman** [comment]
For implementation, since <Tab> currently does nothing (tab complete seems to kick in, in a useless way) how about making <Enter> the "require this module" command and <Tab> the command to open up a menu of exports symbols in the file.

**Comment by megawac** [comment]
I think #5 would be easier to implement (just `ls -R node_modules`) and more useful

**Comment by dantman** [comment]
> I think #5 would be easier to implement (just ls -R node_modules) and more useful

These sound like two completely different use cases. And usefulness is subjective. I personally haven't used any module with sub components like those for while.

**Comment by megawac** [comment]
What I mean is it will be undoubtedly easier to implement, and it tends to be better design (as you don't have to load the entire module for one function).

For example

```js
var chunk = require("lodash/array/chunk");
// vs
var chunk = require("lodash").chunk;
```

The first loads only the stuff necessary for the chunk function whereas the second imports then entire module for the function.

Implementing whats suggested here would require parsing the javascript which a) can be tricky for different export formats (CommonJS vs es6 exports vs old UMD exports)

**Comment by dantman** [comment]
This feature is more for cases like:
```js
var EventEmitter = require('events').EventEmitter;
var HttpServer = require('http').Server;
var highlight = require('highlightjs').highlight;
```

Sub components are only relevant when a module actually supports sub components. Which is only a small handful of modules.

**Comment by ganemone** [comment]
@dantman - What do you mean by <TAB>? I don't believe there is anything in the sublime API that would allow for this. The tab completion feature is there because of the insertion of a snippet, but we don't have access to changing the functionality of a <TAB> press. With regards to subcomponents, vs parsing export formats, I think implementing both would be both useful and doable.

**Comment by ganemone** [comment]
You can track progress on this issue on [this branch](https://github.com/ganemone/NodeRequirer/tree/ExportCommand)

**Comment by dantman** [comment]
@ganemone You're right. I never looked at sublime's API. They really don't provide much to work with.

I can also see why it would be impossible to implement NodeRequirer intuitively (within a completion like box, especially when a user types `require`).
