### ISSUE TITLE
Add option to turn on/off snippets

### ISSUE THREAD

**Issue by ganemone** [ganemone/NodeRequirer#30]
If a user is never using the snippet functionality, it would be annoying to have to tab through the options every time. We should add an option that turns this functionality on or off.

**Comment by dantman** [comment]
+1

4/5 times the snippet functionality just combines with my Tourettes to delete name of the variable and force me to undo to get it back.

I'd prefer to make NodeRequire smarter and smarter until the point I never have to change the variable name after inclusion.
