### ISSUE TITLE
Allow aliasing package.json

### ISSUE THREAD

**Issue by dantman** [ganemone/NodeRequirer#36]
This is a somewhat common pattern:
```js
var pkg = require('../package.json');
```

Perhaps it would be worth letting package.json be aliased with a default of `pkg` (since the default `var package = require('../package.json');` is almost always wrong).

Because package.json is a local the aliases cannot currently match it in a global way. Perhaps we should special case package.json and allow `{ "alias": { "package.json": "pkg" } }` to set it.

**Comment by ganemone** [comment]
+1
