### ISSUE TITLE
Add "ignore" in the config

### ISSUE THREAD

**Issue by ayamflow** [ganemone/NodeRequirer#46]
Would it be possible to add, like in the sublime user config, an array of file types to ignore? I don't want images, DS_Store, etc... To show up when I type.

Thanks for this great plugin - first one that really works for me!

**Comment by ganemone** [comment]
Yes that is possible, and something we should implement.

**Comment by ganemone** [comment]
Added as `file_exclude_patterns`. Also see `exclude_dirs`
