### ISSUE TITLE
Ubuntu is broken again

### ISSUE THREAD

**Issue by megawac** [ganemone/NodeRequirer#50]
Sublime@3074 is broken on Ubuntu Trusty since https://github.com/ganemone/NodeRequirer/commit/075d450f826ff68dad5dcb3ae77c21df9eb0c26c (https://github.com/ganemone/NodeRequirer/commit/8e322259588e85f0dd47504561b464874cfe46f1 was last working commit).

Currently insert won't inject any text

**Comment by dantman** [comment]
Open up the console, usually when NodeRequirer utterly fails there is a stack trace in the console.

**Comment by megawac** [comment]
Yeah, for 075d450 its the same as #40. Current its an issue with resolving `utils.aliased`

```js
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "/home/gyeates/.config/sublime-text-3/Packages/NodeRequirer/NodeRequirer.py", line 344, in run
    module_info = get_module_info(args['module'], self.view)
  File "/home/gyeates/.config/sublime-text-3/Packages/NodeRequirer/NodeRequirer.py", line 396, in get_module_info
    aliased_to = utils.aliased(module_path, view=view)
AttributeError: 'module' object has no attribute 'aliased'
```

**Comment by ganemone** [comment]
Hm... odd that I am not having that issue. Have you quit and restarted sublime recently? I have noticed sublime has some annoying caching issues

**Comment by megawac** [comment]
What build are you using @ganemone?

On Tue, Mar 10, 2015 at 3:38 PM, Giancarlo Anemone <notifications@github.com

**Comment by ganemone** [comment]
8e32225. Works just fine for me on OSX and Ubuntu

**Comment by megawac** [comment]
Which sublime build?

On Tue, Mar 10, 2015 at 3:54 PM, Giancarlo Anemone <notifications@github.com

**Comment by ganemone** [comment]
I have the repo cloned into my packages folder, so I'm working directly off of master.

**Comment by dantman** [comment]
@ganemone is correct about the caching issues. Sublime Text will reload the NodeRequirer module but will not reload any of the modules it depends on.

Which would create this exact situation, where Sublime Text is running a new NodeRequirer but is using old NodeRequirer.src.* modules. The only way "normally" to fix this is to restart Sublime Text.

I also committed a `.build` file which if you've installed [Package Reloader](https://packagecontrol.io/packages/Package%20Reloader) will make Sublime reload the extra modules as well.

**Comment by megawac** [comment]
Are you using 3065 or 3075?

On Tue, Mar 10, 2015 at 3:57 PM, Giancarlo Anemone <notifications@github.com

**Comment by dantman** [comment]
I have 3065.
