### ISSUE TITLE
Import module from cursor hovering over word + command (import-js)

### ISSUE THREAD

**Issue by chenglou** [ganemone/NodeRequirer#59]
https://github.com/trotzig/import-js

Hovering over a word and pressing a shortcut will automatically import the correct module at the top of the file.

**Comment by ganemone** [comment]
Thats a good idea!

**Comment by bsansouci** [comment]
I'd love that too :D

**Comment by ganemone** [comment]
Working on it. Coming soon!

**Comment by ganemone** [comment]
added as of 0.4.3

**Comment by chenglou** [comment]
@ganemone seems like no command works anymore?

**Comment by bsansouci** [comment]
@chenglou @ganemone On mac at least yes, no command seems to work

**Comment by ganemone** [comment]
Just tested on my mac and everything is working fine. Can you try quitting and restarting sublime? If that doesn't work can you check the python console within sublime and look for a stack trace? ctrl+`

**Comment by chenglou** [comment]
Found it, dupe of #62 now
