### ISSUE TITLE
export "exclude directories" array from the core to settings

### ISSUE THREAD

**Issue by asfktz** [ganemone/NodeRequirer#63]
As a React developer I make use of the 'components' folder as part of my app code.
I also aware of the reasons to exclude it.

could you please export the "exclude directories" array from 'ModuleLoader.py' to settings?

**Comment by ganemone** [comment]
Good Idea - Will do

**Comment by ganemone** [comment]
Done as of 0.4.5

**Comment by asfktz** [comment]
thanks! (:
