### ISSUE TITLE
Support ES6 export

### ISSUE THREAD

**Issue by albburtsev** [ganemone/NodeRequirer#67]
ES6 module syntax already finished: http://www.2ality.com/2014/09/es6-modules-final.html

```js
// Named exports
export const sqrt = Math.sqrt;

// Default exports (one per module)
export default class { ... };
```

But current version of plugin doesn't support it: «Unable to find specific exports. Note: We currently only support parsing commonjs style exporting».

Thank you for NodeRequirer!

**Comment by asfktz** [comment]
+1
please

**Comment by sbalay** [comment]
Any update on this? I'm facing the same error: `Unable to find specific exports. Note: We currently only support parsing commonjs style exporting`
