### ISSUE TITLE
Detect import style to use

### ISSUE THREAD

**Issue by megawac** [ganemone/NodeRequirer#74]
I think this could be useful for devs (like me!) who bounce between ES6 and CJS projects. It should be reasonably simple to detect if the `import` keyword is specified within the source.

It would also be nice to detect what quote style to use.

```json
    "import": "detect",

    "quotes": "detect",
```

**Comment by dantman** [comment]
Perhaps detecting quotes might be a good idea. Though occasionally it may behave wrong (if the project doesn't have a standard or is different for require calls, the file has no strings yet, the only string in the file is the exception to the rule). Though still probably a good idea.

Note that if the projects you work on use jscs NodeRequirer will automatically use those instead.
((And if you know of other standard ways projects declare their quote preferences, we can auto-detect those too))

**Comment by tnrich** [comment]
Hey there, 

Amazing tool! By far one of my favorite sublime packages. I think being able to detect the import style would be very beneficial, as well as maybe having a quick way to manually toggle the import style. I find that when working on a project I want to write `import` statements on the front end, and `require` statements on the backend.
