### ISSUE TITLE
Make camelcasing optional

### ISSUE THREAD

**Issue by plestik** [ganemone/NodeRequirer#84]
Hi,

your plugin is a lifesaver! Thank you for your work. However, (AFAICT) since this PR was merged: https://github.com/ganemone/NodeRequirer/pull/75, NodeRequirer always converts imports to CamelCase. I'm almost never importing classes, mostly just functions and objects, so it looks out of place to me. ESLint doesn't like it either. Can this commit be reverted or can CamelCasing be made optional?

**Comment by ganemone** [comment]
Just pushed 1.0.1 which makes it do camel casing the correct way. Now require('something-something') will give you var somethingSomething.

**Comment by plestik** [comment]
Thank you!
